users/views.py
import sqlite3
from flask import Blueprint, render_template, flash, redirect, url_for, request, session
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.security import check_password_hash
from app import users, db
from users.flags import flag_recon
from users.forms import RegisterForm, LoginForm, SearchForm, BlogForm

users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        user = users.query.filter_by(email=form.email.data).first()
        if user:
            flash('Email address already in use', 'error')
            return render_template('register.html', form=form)

        new_user = users(role='user',
                         email=form.email.data,
                         password=form.password.data,
                         flag_recon=0)

        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    form = LoginForm()

    if form.validate_on_submit():
        user = users.query.filter_by(email=form.email.data).first()

        if not user or not check_password_hash(user.password, form.password.data):
            flash('Please check your login details and try again')

            return render_template('login.html', form=form)

        login_user(user)

        return redirect(url_for('users.search'))
    return render_template('login.html', form=form)


@users_blueprint.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm()

    conn = sqlite3.connect('C:/Users/jacob/PycharmProjects/Capture/instance/ctf.db')
    c = conn.cursor()
    res = c.execute("SELECT * FROM products")

    if form.validate_on_submit():
        name = request.form.get('name')
        conn = sqlite3.connect('C:/Users/jacob/PycharmProjects/Capture/instance/ctf.db')
        c = conn.cursor()
        try:
            sql = c.execute("SELECT * FROM products WHERE name LIKE '"'%'+name+'%'"';")
            res = sql.fetchall()
            c.close()
        except TypeError:
            return render_template('search.html', form=form)
        except sqlite3.OperationalError:
            return render_template('search.html', form=form)

        return render_template('search.html', name=name, form=form, res=res)

    return render_template('search.html', form=form, res=res)


@users_blueprint.route('/reconnaissance')
def reconnaissance():
    return render_template('reconnaissance.html')


@users_blueprint.route('/tasks')
def tasks():
    return render_template('tasks.html')


@users_blueprint.route('/submit', methods=['GET', 'POST'])
def submit():

    form = SearchForm()

    conn = sqlite3.connect('C:/Users/jacob/PycharmProjects/Capture/instance/ctf.db')
    c = conn.cursor()
    sql = c.execute("SELECT flag_recon FROM users WHERE id=?", (current_user.id,))
    flag_value_rec1 = sql.fetchone()

    if form.validate_on_submit():
        name = request.form.get('name')

        if name == flag_recon:
            c.execute("UPDATE users SET flag_recon = 1 WHERE id=?", (current_user.id,))
            conn.commit()
            flash('Correct flag, well done!', 'success')
        else:
            flash('Incorrect flag, try again!', 'error')

        sql = c.execute("SELECT flag_recon FROM users WHERE id=?", (current_user.id,))
        flag_value_rec1 = sql.fetchone()
        c.close()

        return render_template('submit.html', form=form, flag_value_rec1=flag_value_rec1)
    c.close()
    return render_template('submit.html', form=form, flag_value_rec1=flag_value_rec1)


@users_blueprint.route('/blogs', methods=['GET', 'POST'])
def blogs():

    conn = sqlite3.connect('C:/Users/jacob/PycharmProjects/Capture/instance/ctf.db')
    c = conn.cursor()

    sql = c.execute("SELECT * FROM comments")
    all_posts = sql.fetchall()

    form = BlogForm()
    if form.validate_on_submit():
        post = request.form.get('content')
        c.execute("INSERT INTO comments(comment) VALUES (?)", (post,))
        conn.commit()
        c.close()
        return redirect(url_for('users.blogs'))

    return render_template('blogs.html', form=form, all_posts=all_posts)


@users_blueprint.route('/delete', methods=['GET', 'POST'])
def delete():
    conn = sqlite3.connect('C:/Users/jacob/PycharmProjects/Capture/instance/ctf.db')
    c = conn.cursor()
    c.execute("DELETE FROM comments")
    conn.commit()
    c.close()
    return blogs()


@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

templates/account.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

templates/admin-home.html
{% extends "base.html" %}

{% block content %}
    <h1>admin home</h1>
{% endblock %}

templates/adminhome.html
{% extends "base.html" %}

{% block content %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
    <link rel="stylesheet" href="/static/style.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="/static/script.js"></script>
</head>
<body>
    <nav class="navbar">
        <div class="content">
            <div class="logo"><a href="#">Capture the Flag</a></div>
            <ul class="menu-list">
                <li><a href="{{ url_for('index') }}">Home</a></li>
                {% if not current_user.is_authenticated %}
                    <li><a href="{{ url_for('users.login') }}">Login</a></li>
                    <li><a href="{{ url_for('users.register') }}">Register</a></li>
                {% endif %}
            {% if current_user.is_authenticated and current_user.role=='admin'%}
                <li><a href="{{ url_for('admin.privileges') }}">Admin</a></li>
            {% endif %}
            {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('users.tasks') }}">Tasks</a></li>
                <li><a href="{{ url_for('users.search') }}">Search</a></li>
                <li><a href="{{ url_for('users.submit') }}">Submit</a></li>
                <li><a href="{{ url_for('users.blogs') }}">Blogs</a></li>
                <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
            {% endif %}
            </ul>
        </div>
    </nav>
{% block content %}
{% endblock %}
</body>
</html>

templates/blogs.html
{% extends "base.html" %}
{% block content %}
{% autoescape false %}
<div class="container">
    <form method="POST" action="{{ url_for('users.blogs') }}">
        {{ form.csrf_token() }}
        {{ form.content(class="text-box", placeholder="Blog to the world!") }}
        {{ form.submit(class="blog-submit") }}
    </form>
</div>
<div class="small-container">
    <form method="POST" action="{{ url_for('users.delete') }}" class="">
        {{ form.csrf_token() }}
        {{ form.delete_submit(class="blog-submit", placeholder="Delete all posts") }}
    </form>
</div>
<div class="small-container">
{% for post in all_posts %}

    {{ post[0] }}

{% endfor %}
</div>
{% endautoescape %}
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<div>
  {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, error in messages %}
            {% if category == 'error' %}
              <div class="alert" role="alert">
            {% else %}
              <div class="alert" role="alert">
            {% endif %}
              {{ error }}
            </div>
        {% endfor %}
      {% endif %}
  {% endwith %}

<form method="POST" >
<div class="box">
    <div class="login-container">
        <div class="top-header">
            <span>Have an account?</span>
            <header>Login</header>
        </div>
        {{ form.csrf_token() }}
        <div class="input-field">
            <label for="uname"><b>Email</b>
                {{ form.email(class="input", placeholder="Email") }}
                {% for error in form.email.errors %}
                    {{ error }}
                {% endfor %}
            </label>
        </div>
        <div class="input-field">
            <label for="psw"><b>Password</b>
                {{ form.password(type="password", class="input", placeholder="Password") }}
                {% for error in form.password.errors %}
                    {{ error }}
                {% endfor %}
            </label>
        </div>
        <div class="input-field">
            <label for="sub"><b>Submit</b></label>
            {{ form.submit(class="submit") }}

        </div>
        <div class="bottom">
            <div class="left">
                <input type="checkbox" id="check">
                <label for="check">Remember Me</label>
            </div>
            <div class="right">
                <label><a href="#">Forgot password?</a></label>
            </div>
        </div>
    </div>
</div>
</form>
<h2>Hints
    <a id="hint-num">0</a>/3
    (
    <a href="#" onclick="showHint(); return false">show</a>
    )
</h2>
<div id="hints">
    <ol>
        <li style="display: none" data-hidden="true">
            <b>1.</b>
            This login form doesn't limit the amount of login attempts.
        </li>
        <li style="display: none" data-hidden="true">
            <b>2.</b>
            If you're able to find an admins email, you could brute force log in.
        </li>
        <li style="display: none" data-hidden="true">
            <b>3.</b>
            Using a Kali Linux virtual machine, there are tools such as John the Ripper or Hydra to crack passwords,
            which can use built-in wordlists such as rockyou.txt.
        </li>
    </ol>
</div>
{% endblock %}

templates/privileges.html
{% extends "base.html" %}

{% block content %}
<body>
<div class="container">
    <form method="POST" action="{{ url_for('admin.privileges') }}" class="search-bar">
        {{ form.csrf_token() }}
        <label>
            {{ form.name(class="name", placeholder="Enter ID of User to give admin") }}
        </label>
        {{ form.submit(class="small-submit") }}
    </form>
</div>
<table>
    <tr>
        <th>User ID</th>
        <th>Role</th>
        <th>Email</th>
    </tr>
{% for row in res %}
    <tr>
        <td>{{ row[0] }}</td>
        <td>{{ row[1] }}</td>
        <td>{{ row[2] }}</td>
    </tr>
{% endfor %}
</table>
</body>
{% endblock %}

templates/reconnaissance.html
{% extends "base.html" %}

{% block content %}
<div class="footer">
<ul>
    <li>
        <a href="https://github.com/JacobKing21/Capture">
            <img class="git" src="/static/git.png" alt="git logo">
        </a>
    </li>
    <li>
        <a href="https://twitter.com/SteveMerchCTF">
            <img class="twitter" src="/static/twitter.png" alt="twitter logo">
        </a>
    </li>
</ul>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, error in messages %}
            {% if category == 'error' %}
              <div class="alert" role="alert">
            {% else %}
              <div class="alert" role="alert">
            {% endif %}
              {{ error }}
            </div>
        {% endfor %}
      {% endif %}
  {% endwith %}
</div>
<body>
<form method="POST">
{{ form.csrf_token() }}
<div class="box">
    <div class="login-container">
        <div class="top-header">
            <header>Register</header>
        </div>

        <div class="input-field">
            <label for="email"><b>Email</b>
                {{ form.email(type="text", class="input", placeholder="Email") }}
                {% for error in form.email.errors %}
                    {{ error }}
                {% endfor %}
            </label>
        </div>
        <div class="input-field">
            <label for="psw"><b>Password</b>
                {{ form.password(type="password", class="input", placeholder="Password") }}
                {% for error in form.password.errors %}
                    {{ error }}
                {% endfor %}
            </label>
            <label for="confirmPsw"><b>Confirm Password</b>
                {{ form.confirm_password(type="password" ,class="input", placeholder="Confirm Password") }}
                {% for error in form.confirm_password.errors %}
                    {{ error }}
                {% endfor %}
            </label>

        </div>
        <div class="input-field padding-top">
            <label for="sub"></label>
            <input type="submit" class="submit" value="Register">

        </div>
        <div class="bottom">
            <div class="left">
                <input type="checkbox" id="check">
                <label for="check">Remember Me</label>
            </div>
            <div class="right">
                <label><a href="#">Forgot password?</a></label>
            </div>
        </div>
    </div>
</div>
    </form>
</body>
{% endblock %}

templates/search.html
{% extends "base.html" %}

{% block content %}
<body>
<div class="container">
    <form method="POST" action="{{ url_for('users.search') }}" class="search-bar">
        {{ form.csrf_token() }}
        <label>
            {{ form.name(class="name", placeholder="search anything") }}
        </label>
        {{ form.submit(class="small-submit") }}
    </form>
</div>
<table>
    <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
    </tr>
{% for row in res %}
    <tr>
        <td>{{ row[1] }}</td>
        <td>{{ row[2] }}</td>
        <td>{{ row[3] }}</td>
    </tr>
{% endfor %}
</table>

<h2>Hints
    <a id="hint-num">0</a>/3
    (
    <a href="#" onclick="showHint(); return false">show</a>
    )
</h2>
<div id="hints">
    <ol>
        <li style="display: none" data-hidden="true">
            <b>1.</b>
            This search bar is connected to a SQLite database which is vulnerable to an SQL injection attack.
        </li>
        <li style="display: none" data-hidden="true">
            <b>2.</b>

        </li>
        <li style="display: none" data-hidden="true">
            <b>3.</b>
            This is hint 3
        </li>
    </ol>
</div>
</body>
{% endblock %}

templates/submit.html
{% extends "base.html" %}
{% block content %}
<body>
<div class="container">
    <form method="POST" action="{{ url_for('users.submit') }}" class="search-bar">
        {{ form.csrf_token() }}
        <label>
            {{ form.name(class="name", placeholder="Submit Flags") }}
        </label>
        {{ form.submit(class="small-submit") }}
    </form>
</div>
{% if flag_value_rec1 == (0,) %}
<h3>Reconnaissance Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
{% endif %}
{% if flag_value_rec1 == (1,) %}
<div class="meter">
	<span style="width: 100%"></span>
</div>
{% endif %}
<h3>Resource Development Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Initial Access Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Execution Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Persistence Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Privilege Escalation Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Defense Evasion Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Credential Access Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Discovery Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Lateral Movement Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Collection Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Command and Control Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Exfiltration Progress</h3>
<div class="meter">0%
	<span style="width: 0"></span>
</div>
<h3>Impact Progress</h3>
<div class="meter">0%
	<span style="width: 0">0%</span>
</div>
{% endblock %}

templates/tasks.html
{% extends "base.html" %}

{% block content %}
<div class="ag-format-container">
  <div class="ag-courses_box">
    <div class="ag-courses_item">
      <a href="{{ url_for('users.reconnaissance') }}" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Reconnaissance
        </div>
      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Resource Development
        </div>
      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Initial Access
        </div>
      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Execution
        </div>
      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Persistence
        </div>
      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Privilege Escalation
        </div>
      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg">
        </div>
        <div class="ag-courses-item_title">
          Defence Evasion
        </div>
      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Credential Access
        </div>

      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Discovery
        </div>

      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Lateral Movement
        </div>

      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Collection
        </div>

      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Command and Control
        </div>

      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Exfiltration
        </div>

      </a>
    </div>

    <div class="ag-courses_item">
      <a href="#" class="ag-courses-item_link">
        <div class="ag-courses-item_bg"></div>

        <div class="ag-courses-item_title">
          Impact
        </div>

      </a>
    </div>


  </div>

</div>
{% endblock %}